//! The Windows shell's P/Invoke declarations are generated from this crate's `extern "C"`
//! functions and `#[repr(C)]` types by csbindgen, and checked in; this fails while they are stale.
//! Regenerate with `INK_WRITE_BINDING=1 cargo test -p ink-ffi --test csharp_binding`.
//!
//! `inkwell.h` stays the contract (it is hand-written, as is the Rust side); the C# is generated so
//! it cannot drift from the Rust signatures. csbindgen reads only literal constants (not `-1` or
//! `1 << 20`), so the header's constants are written here from the crate's own values instead.

use std::path::{Path, PathBuf};

/// Where the generated C# lives, from the repository root.
const OUT: &str = "windows/Inkwell.Core/Generated/NativeMethods.g.cs";

fn crate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// `inkwell.h`'s constants, with the values the crate compiles.
fn constants() -> String {
    let ints: [(&str, &str, i64); 7] = [
        ("Ok", "INK_OK", ink_ffi::INK_OK.into()),
        (
            "NotInitialized",
            "INK_ERR_NOT_INITIALIZED",
            ink_ffi::INK_ERR_NOT_INITIALIZED.into(),
        ),
        (
            "AlreadyInitialized",
            "INK_ERR_ALREADY_INITIALIZED",
            ink_ffi::INK_ERR_ALREADY_INITIALIZED.into(),
        ),
        (
            "InvalidArgument",
            "INK_ERR_INVALID_ARGUMENT",
            ink_ffi::INK_ERR_INVALID_ARGUMENT.into(),
        ),
        ("Failed", "INK_ERR_FAILED", ink_ffi::INK_ERR_FAILED.into()),
        (
            "UnknownCall",
            "INK_ERR_UNKNOWN_CALL",
            ink_ffi::INK_ERR_UNKNOWN_CALL.into(),
        ),
        ("Panic", "INK_ERR_PANIC", ink_ffi::INK_ERR_PANIC.into()),
    ];
    let mut out = String::from(
        "\nnamespace Inkwell.Core.Native\n{\n    \
         /// <summary>\n    \
         ///  The status codes the C ABI returns (INK_OK, INK_ERR_* in inkwell.h).\n    \
         /// </summary>\n    \
         internal static class InkStatus\n    {\n",
    );
    for (name, c, value) in ints {
        out.push_str(&format!(
            "        /// <summary>{c}</summary>\n        internal const int {name} = {value};\n"
        ));
    }
    out.push_str("    }\n\n    /// <summary>\n    ///  The C ABI's other constants (inkwell.h).\n    /// </summary>\n    internal static class InkAbi\n    {\n");
    for (name, c, value) in [
        (
            "Version",
            "INK_ABI_VERSION",
            u64::from(ink_ffi::events::ABI_VERSION),
        ),
        ("MaxJson", "INK_MAX_JSON", ink_ffi::INK_MAX_JSON as u64),
        (
            "EngineOffline",
            "INK_ENGINE_OFFLINE",
            ink_ffi::external::KIND_OFFLINE.into(),
        ),
        (
            "EngineStreaming",
            "INK_ENGINE_STREAMING",
            ink_ffi::external::KIND_STREAMING.into(),
        ),
        (
            "EngineLlm",
            "INK_ENGINE_LLM",
            ink_ffi::external::KIND_LLM.into(),
        ),
    ] {
        out.push_str(&format!(
            "        /// <summary>{c}</summary>\n        internal const uint {name} = {value};\n"
        ));
    }
    out.push_str("    }\n}\n");
    out
}

fn generate(to: &Path) {
    csbindgen::Builder::default()
        .input_extern_file(crate_dir().join("src/lib.rs"))
        .input_extern_file(crate_dir().join("src/external.rs"))
        .csharp_dll_name("ink_ffi")
        .csharp_namespace("Inkwell.Core.Native")
        .csharp_class_name("NativeMethods")
        .csharp_class_accessibility("internal")
        .csharp_use_function_pointer(true)
        .csharp_file_header(
            "// Generated by csbindgen from core/crates/ink-ffi (the C ABI, inkwell.h). Regenerate with\n\
             // `INK_WRITE_BINDING=1 cargo test -p ink-ffi --test csharp_binding`.",
        )
        .csharp_file_footer(constants())
        .generate_csharp_file(to)
        .expect("csbindgen reads the crate");
}

#[test]
fn the_generated_csharp_binding_is_current() {
    let checked_in = crate_dir().join("../../..").join(OUT);
    if std::env::var_os("INK_WRITE_BINDING").is_some() {
        generate(&checked_in);
        return;
    }
    let fresh = std::env::temp_dir().join(format!("ink-ffi-binding-{}.g.cs", std::process::id()));
    generate(&fresh);
    let generated = std::fs::read_to_string(&fresh).unwrap();
    let _ = std::fs::remove_file(&fresh);
    // A Windows checkout may turn line ends into CRLF; the content is what must match.
    let current = std::fs::read_to_string(&checked_in)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    assert!(
        current == generated.replace("\r\n", "\n"),
        "{OUT} is stale: run `INK_WRITE_BINDING=1 cargo test -p ink-ffi --test csharp_binding`"
    );
}
