[package]
name = "ink-platform-mac"
description = "objc2 implementations of the platform traits on macOS."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ink-core.workspace = true
